name: CI/CD Pipeline Inmutable (GitHub Packages)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-or-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Ejecutar Release Please para automatizar versiones y PRs
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      # 2. Descargar el código (solo si se creó una nueva release)
      - name: Checkout del código
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      # 3. Autenticación en GHCR (solo si se creó una nueva release)
      - name: Autenticación en GHCR
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Construir y subir la imagen directamente a tu perfil de GitHub
      - name: Construir y Subir Imagen Docker
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.release.outputs.tag_name }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest